// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, Wrapper, print, wrapper;

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  Wrapper = require('../lib/xapi-wrapper.js');

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '201870';

  PASSWORD = 'rz3smI';

  print = function(msg) {
    console.log(msg);
  };

  wrapper = new Wrapper(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  wrapper.on('open', function() {
    print('Successfuly connected, login in');
    return wrapper.login();
  });

  wrapper.on('close', function() {
    return print('Connection closed');
  });

  wrapper.on('error', function() {
    return print('Connection error');
  });

  wrapper.on('login', function(error, req, res) {
    print("Received response to command login");
    print("This is the request: " + req + " \nThis is the response " + res);
    print("login out");
    return wrapper.logout();
  });

  wrapper.on('logout', function(error, req, res) {
    return print("logged out hopefully");
  });

  wrapper.connect();

}).call(this);
