// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, Wrapper, autoRedirect, plugins, print, wrapper;

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  Wrapper = require('../lib/xapi-wrapper.js');

  plugins = require("xapi-plugins");

  autoRedirect = plugins.autoRedirect;

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '201870';

  PASSWORD = 'rz3smI';

  print = function(msg) {
    console.log(msg);
  };

  wrapper = new Wrapper(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  wrapper.use(autoRedirect);

  wrapper.on('open', function() {
    print('Successfuly connected, login in');
    return wrapper.login();
  });

  wrapper.on('login', function(req, res) {
    print("Succesfuly logged in, connecting to stream");
    return wrapper.connectStream();
  });

  wrapper.on('logout', function(req, res) {
    print("Successfuly loged out");
    wrapper.disconnectStream();
    return wrapper.disconnect();
  });

  wrapper.on('apiError', function(req, err) {
    print("The api returned a negative response to request: " + (JSON.stringify(req, null, 4)));
    return print("" + (JSON.stringify(err, null, 4)));
  });

  wrapper.onStream('open', function() {
    print("Successfuly connected to stream, subscribing to indicators and EURUSD tick prices");
    wrapper.subscribeAccountIndicators();
    return wrapper.subscribeTickPrices({
      symbols: ['EURUSD']
    });
  });

  wrapper.onStream('indicators', function(msg) {
    return print("Received indicator data: " + (JSON.stringify(msg, null, 4)));
  });

  wrapper.onStream('tickPrices', function(msg) {
    return print("Received tick prices: " + (JSON.stringify(msg, null, 4)));
  });

  wrapper.connect();

  setTimeout(function() {
    print('Login out');
    return wrapper.logout();
  }, 10000);

}).call(this);
