// Generated by CoffeeScript 1.7.1
(function() {
  var CONN_PORT, PASSWORD, SERVER_URL, STREAM_PORT, USERNAME, Wrapper, print, wrapper;

  process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

  Wrapper = require('../lib/xapi-wrapper.js');

  SERVER_URL = 'xapia.x-station.eu';

  CONN_PORT = '5144';

  STREAM_PORT = '5145';

  USERNAME = '201870';

  PASSWORD = 'rz3smI';

  print = function(msg) {
    console.log(msg);
  };

  wrapper = new Wrapper(SERVER_URL, CONN_PORT, STREAM_PORT, USERNAME, PASSWORD);

  wrapper.on('open', function() {
    print('Successfuly connected, login in');
    return wrapper.login('hello login');
  });

  wrapper.on('close', function() {
    return print('Connection closed');
  });

  wrapper.on('error', function() {
    return print('Connection error');
  });

  wrapper.on('login', function(err, req, res) {
    print("Received response to command login");
    print("This is the request: " + (JSON.stringify(req)) + " \nThis is the response " + (JSON.stringify(res)));
    wrapper.ping(null, function(err, req, res) {
      return print("Piiiing");
    });
    print("login out");
    return wrapper.logout(null, function(err, req, res) {
      print("This is a direct callback for this particular logout request: " + (JSON.stringify(req)) + ". The response is " + (JSON.stringify(res)));
      return wrapper.disconnect();
    });
  });

  wrapper.connect();

}).call(this);
