// Generated by CoffeeScript 1.7.1
(function() {
  var Connector, Emitter, Wrapper;

  Connector = require('xapi-connector');

  Emitter = require('events').EventEmitter;

  Wrapper = (function() {
    function Wrapper(server_url, conn_port, stream_port, username, password) {
      this.server_url = server_url;
      this.conn_port = conn_port;
      this.stream_port = stream_port;
      this.username = username;
      this.password = password;
      this.conn_status = 0;
      this.stream_status = 0;
      this._req_id = 0;
      this._requests = {};
      this._emitter = new Emitter();
      this._streamEmitter = new Emitter();
      this._connector = new Connector(this.server_url, this.conn_port, this.stream_port, this.username, this.password);
      this._connector.on('open', (function(_this) {
        return function() {
          _this.conn_status = 1;
          return _this._emitter.emit('open');
        };
      })(this));
      this._connector.on('close', (function(_this) {
        return function() {
          _this.conn_status = 2;
          return _this._emitter.emit('close');
        };
      })(this));
      this._connector.on('error', (function(_this) {
        return function() {
          _this.conn_status = 3;
          return _this._emitter.emit('error');
        };
      })(this));
      this._connector.on('message', (function(_this) {
        return function(msg) {
          return _this._emitter.emit('_message', msg);
        };
      })(this));
    }

    Wrapper.prototype.on = function(event, callback) {
      return this._emitter.on(event, callback);
    };

    Wrapper.prototype._send = function(req_obj) {
      var args, command, customTag, req, req_id;
      req_id = this._req_id += 1;
      this._requests.req_id = req_obj;
      command = req_obj.command;
      args = req_obj["arguments"];
      customTag = req_obj.customTag = req_id;
      req = this._connector.buildCommand(command, args, customTag);
      return this._connector.send(req);
    };

    Wrapper.prototype.login = function(args, customTag) {
      var req_obj;
      req_obj = {
        command: 'login',
        "arguments": args,
        customTag: customTag
      };
      return this._send(req_obj);
    };

    Wrapper.prototype.connect = function() {
      return this._connector.connect();
    };

    return Wrapper;

  })();

}).call(this);
